### ISSUE TITLE
links to docs

### ISSUE THREAD

**Issue by raedah** [planetdecred/website#4]
Should include some links to primary sources about decred. Can discuss.

https://docs.decred.org/
https://devdocs.decred.org/

**Comment by ghost** [comment]
I think it's a very good idea. Would it look good in a drop-down "docs"?

**Comment by ghost** [comment]
something like that? 

![2020-02-19_1008](https://user-images.githubusercontent.com/60282692/74851260-9ac61680-5300-11ea-850e-6c95b359c420.png)

**Comment by raedah** [comment]
Space in the middle isnt needed. Can flow like a single paragraph.
